#Basic Tricks

tricklist = [
"Backside 180",
"Backside 360",
"Backside Caballerial",
"Backside Half Cab",
"Fakie Ollie",
"Frontside 180",
"Frontside 360",
"Frontside Caballerial",
"Frontside Half Cab",
"Nollie",
"Nollie Backside 180",
"Nollie Backside 360",
"Nollie Frontside 180",
"Nollie Frontside 360",
"Ollie",
"Ollie North",
"Ollie South",
"Powerslide",
"Switch Backside 180",
"Switch Backside 360",
"Switch Frontside 180",
"Switch Frontside 360",
"Switch Ollie",
"360 Flip",
"360 Hardflip",
"360 Ollie Heelflip",
"360 Ollie Kickflip",
"360 Pop Shove-it",
"360 Shuvit",
"540 Flip",
"720 Flip",
"Backside Bigspin",
"Backside Flip",
"Backside Half Cab Heelflip",
"Backside Half Cab Kickflip",
"Backside Heelflip",
"Backside Kickflip",
"Big Heelflip",
"Bigflip",
"Biggerflip",
"Biggerspin",
"Bigspin",
"Caballerial Flip",
"Double Heelflip",
"Double Kickflip",
"Fakie 360 Flip",
"Fakie 360 Hardflip",
"Fakie Backside Bigspin",
"Fakie Backside Pop Shove-it",
"Fakie Frontside Bigspin",
"Fakie Frontside Pop Shove-it",
"Fakie Hardflip",
"Fakie Heelflip",
"Fakie Inward Heelflip",
"Fakie Kickflip",
"Fakie Varial Heelflip",
"Fakie Varial Kickflip",
"Forward Flip",
"Frontside 360 Pop Shove it",
"Frontside Bigspin",
"Frontside Flip",
"Frontside Half Cab Heelflip",
"Frontside Half Cab Kickflip",
"Frontside Heelflip",
"Frontside Kickflip",
"Frontside Pop Shove-it",
"Gazelle Flip",
"Gazelle Spin",
"Ghetto Bird",
"Half Cab",
"Hardflip",
"Heelflip",
"Inward Heelflip",
"Kickflip",
"Laser Flip",
"Nollie 360 Flip",
"Nollie 360 Hardflip",
"Nollie 360 Pop Shove-it",
"Nollie Backside Bigspin",
"Nollie Backside Heelflip",
"Nollie Backside Kickflip",
"Nollie Backside Pop Shove-it",
"Nollie Frontside Bigspin",
"Nollie Frontside Heelflip",
"Nollie Frontside Kickflip",
"Nollie Frontside Pop Shove-it",
"Nollie Hardflip",
"Nollie Heelflip",
"Nollie Impossible",
"Nollie Inward Heelflip",
"Nollie Kickflip",
"Nollie Laser Flip",
"Nollie Varial Heelflip",
"Nollie Varial Kickflip",
"Shuvit",
"Switch 360 Flip",
"Switch 360 Hardflip",
"Switch Backside Bigspin",
"Switch Backside Heelflip",
"Switch Backside Kickflip",
"Switch Backside Pop Shove-it",
"Switch Frontside Bigspin",
"Switch Frontside Heelflip",
"Switch Frontside Kickflip",
"Switch Frontside Pop Shove-it",
"Switch Hardflip",
"Switch Heelflip",
"Switch Inward Heelflip",
"Switch Kickflip",
"Switch Laser Flip",
"Switch Varial Heelflip",
"Switch Varial Kickflip",
"Triple Kickflip",
"Varial Heelflip",
"Varial Kickflip"]