#Grind and Slide Tricks
tricklist = ["50-50 Grind",
"Backside 5-0",
"Backside 50-50",
"Backside Bluntslide",
"Backside Boardslide",
"Backside Crooked",
"Backside Feeble",
"Backside Lipslide",
"Backside Noseblunt Slide",
"Backside Nosegrind",
"Backside Noseslide",
"Backside Overcrook",
"Backside Salad",
"Backside Smith",
"Backside Suski",
"Backside Tailslide",
"Barley Grind",
"Bertlemann Slide",
"Bluntslide",
"Boardslide",
"Casper Slide",
"Crail Slide",
"Crooked Grind",
"Darkslide",
"Feeble Grind",
"Frontside 5-0",
"Frontside 50-50",
"Frontside Bluntslide",
"Frontside Boardslide",
"Frontside Crooked",
"Frontside Feeble",
"Frontside Lipslide",
"Frontside Noseblunt Slide",
"Frontside Nosegrind",
"Frontside Noseslide",
"Frontside Overcrook",
"Frontside Salad",
"Frontside Smith",
"Frontside Suski",
"Frontside Tailslide",
"Hurricane",
"Hurricane Grind",
"Layback Grind",
"Lipslide",
"Nail Slide",
"Noseblunt Slide",
"Nosegrind",
"Noseslide",
"Overcrook Grind",
"Overturn",
"Primo Grind",
"Salad Grind",
"Slash Grind",
"Smith Grind",
"Suski Grind",
"Tailblock Grind",
"Tailslide",
"Willy Grinds"]
